---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products":
    post:
      summary: Creates a product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: product created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                category_id:
                  type: integer
              required:
              - title
              - category_id
          application/xml:
            schema:
              type: object
              properties:
                title:
                  type: string
                category_id:
                  type: integer
              required:
              - title
              - category_id
  "/products/{id}":
    get:
      summary: Retrieves a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  category:
                    type: object
                required:
                - id
                - title
                - category
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  category:
                    type: object
                required:
                - id
                - title
                - category
        '404':
          description: product not found
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
